"""Per-video direction for the video-prompt builder.

Scripts are NOT stored here: build_video_prompts.py reads them from each
character's content-plan.md, so the spoken words always match the plan.

beats: (phrase from the script, what the face/hands do). Timing is computed
from where the phrase sits in the script.
"""

V = {}

# ---------------------------------------------------------------- ROSA
V["rosa"] = [
    dict(id="R1", fmt="A", loc="kitchen", light="morning", outfit="default",
         cam=("propped", "a wooden bread board leaning on the wall at the back of the kitchen table, a little below her eye level"),
         framing="Near-frontal medium close-up, chest-up. She sits at the table with her forearms on the crochet cloth, a touch off-center; the window and the blue-and-white tiles are soft behind her.",
         props="a small white coffee cup on a saucer on the cloth beside her hand (static, never moves)",
         direction="the opener of a series: a 94-year-old enjoying listing her own rules, delighted with herself",
         motive="she has outlived everyone who told her to slow down; her 'nevers' are trophies",
         goal="make the viewer laugh AND want part two",
         obstacle="the lift item collapses mid-list and she has to rescue it without losing the rhythm",
         tactic="she counts the 'nevers' on her fingers and checks the lens after each one: did it land?",
         beats=[("Things I never do", "chin up, a proud little smile, eyes straight into the lens"),
                ("I never eat standing up", "one finger up, deadly serious"),
                ("like a seagull", "a quick pecking mime with her fingers, then a laugh breaks through"),
                ("I never take the lift", "a second finger goes up, then her face falls as she realises; the register breaks and she waves the point away"),
                ("A hundred and twelve steps", "a proud nod, a thumb pointing down toward the sea"),
                ("And I never look at the telephone", "a third finger, leaning in to the lens, mock-stern"),
                ("Giulia hates this one", "her eyes flick off-lens toward Giulia, mischievous"),
                ("Part two next week", "back to the lens, a sly closed-lip smile")],
         centerpiece="THE COLLAPSE: the lift item falling apart and her waving it away",
         final="she holds the sly smile one beat and raises her eyebrows once: case closed",
         physics="linen sleeves creasing at the elbow, the coral beads shifting as she leans, dust motes in the window light",
         mood="mischievous, warm, quick",
         first_frame="sitting at the kitchen table, forearms on the white crochet cloth, chest-up, a sly closed-lip smile into the lens, a small coffee cup beside her hand",
         split="That counts."),
    dict(id="R2", fmt="A", loc="rocks", light="morning", outfit="swim",
         cam=("companion", "at chest height, standing on the rock one step away and angled slightly down at her"),
         framing="Medium shot. She sits on the flat rock beside the old metal ladder, the towel round her shoulders, the turquoise bay and the headland behind her, a touch off-center.",
         props="the striped towel round her shoulders (moves only with her body and the breeze)",
         direction="the just-came-out moment: wet, alive and a little smug",
         motive="eighty-five years of mornings; this swim is her proof",
         goal="make the viewer feel the cold and want it anyway",
         obstacle="Giulia filming instead of helping, the breeze, her own laughter",
         tactic="she talks to the lens like a friend who doubted her, eyes checking after each jab",
         beats=[("Ninety-four, and I just came out", "a big open grin, water dripping from her hairline, chin lifted at the lens"),
                ("Cold?", "eyebrows up, mock-offended"),
                ("it's not soup", "a flat-hand chop, deadpan"),
                ("you say a bad word", "a wicked little laugh, fingers to her mouth"),
                ("I never go alone", "a nod, serious for one beat: the safety line lands"),
                ("today I have Giulia", "eyes flick up to Giulia above the lens, a teasing squint"),
                ("Useless, but she's here", "a laugh, a little pat of the air toward Giulia"),
                ("The sea doesn't care", "THE SIGNATURE: two fingertips tap the red coral beads twice; her voice drops, eyes steady on the lens"),
                ("It only cares that you come", "a small closed-lip smile")],
         centerpiece="THE SIGNATURE on the catchphrase",
         final="she looks out at the sea for a second, then back at the lens with a tiny nod",
         physics="water droplets running from her hairline, the towel edge lifting in the breeze, wet glossy coral beads, a wet patch on the linen",
         mood="bright, alive, cheeky, then a quiet landing",
         first_frame="sitting on the flat limestone rock beside the old metal ladder, wet slicked-back silver hair, the striped towel round her shoulders over the open white linen shirt and black swimsuit, grinning at the lens, the turquoise bay behind",
         split="Everybody says the bad word."),
    dict(id="R3", fmt="A", loc="doorstep", light="morning", outfit="doorstep",
         cam=("propped", "a terracotta pot of red geraniums on the doorstep, slightly below her eye level"),
         framing="Medium shot from slightly below. She sits on the low wooden stool by the blue door; a soft edge of geranium leaves is in the near foreground.",
         props=None,
         direction="doorstep gossip about her very young doctor",
         motive="she adores the boy, but she loves being the one who knows best",
         goal="land the double punchline",
         obstacle="she mustn't sound like she's mocking doctors; she respects him",
         tactic="she plays both parts, the serious doctor and herself, eyes on the lens for the punchlines",
         beats=[("My doctor is sixty years younger", "a delighted, scandalised look straight into the lens"),
                ("Little beard, like a goat", "she strokes an imaginary goatee on her own chin"),
                ("he listens to my chest", "she mimes a doctor peering at papers, at the lens, then at the papers again"),
                ("Signora, keep doing", "a solemn deep-voiced imitation, chin tucked"),
                ("I wasn't asking", "a sharp little shrug, eyes sparkling: the first punchline"),
                ("No, no, I listen to him", "both palms up, suddenly sincere"),
                ("He says I'm his favorite", "a proud chin lift"),
                ("He says that to everybody", "her face drops into deadpan for the second punchline; a beat of silence")],
         centerpiece="THE DEADPAN on the last line",
         final="she breaks into a short laugh and looks away down the alley",
         physics="the cardigan sleeve sliding up her right wrist during the goatee mime to show the faded anchor tattoo, the stool creaking, the sheets moving overhead",
         mood="gossipy, warm, sharp timing",
         first_frame="sitting on the low wooden stool by the weathered blue door, grey cardigan over the cornflower-blue housedress, hands on her knees, a scandalised, delighted look at the lens",
         split="he looks at the papers again."),
    dict(id="R4", fmt="A", loc="kitchen", light="morning", outfit="default",
         cam=("propped", "the bowl of lemons on the kitchen table, a little below her eye level"),
         framing="Medium close-up, chest-up, she leans slightly toward the lens over the table; lemons soft in the near foreground; the bright window at frame left.",
         props=None,
         direction="a no-nonsense intervention for a tired thirty-year-old",
         motive="she watches Giulia's generation wake up already exhausted, and it baffles her",
         goal="make the viewer try the window tomorrow",
         obstacle="she knows they'll roll their eyes at something this simple",
         tactic="she catches them out with 'the telephone', then sells the tiny secret like it's gold",
         beats=[("Thirty and tired", "a squint at the lens, sizing the viewer up"),
                ("The telephone.", "she points straight at the lens: caught you"),
                ("somebody's wedding", "a theatrical eye-roll"),
                ("I open the window", "she gestures to the window at her left; light catches her face"),
                ("That's the big secret", "a conspiratorial lean-in, almost a whisper"),
                ("Not a little one, a big one", "her hands show a big glass, insistent"),
                ("I wrote you thirty mornings", "a softer, proud smile"),
                ("Giulia put it in the link", "her eyes flick off-lens to Giulia, a little nod")],
         centerpiece="THE BIG SECRET, almost whispered",
         final="she sits back and folds her arms, satisfied",
         physics="the lemons rocking very slightly as the phone settles against the bowl, linen creasing, window light on her face",
         mood="brisk, bossy-loving, conspiratorial",
         first_frame="sitting at the kitchen table, leaning slightly toward the lens with a squint of assessment, the bowl of lemons in the near foreground, the small window bright at the left",
         split="That's the big secret."),
    dict(id="R5", fmt="A", loc="doorstep", light="morning", outfit="doorstep",
         cam=("companion", "at chest height, standing in the alley one step away"),
         framing="Medium shot. She sits on the low stool by the blue door, a touch off-center, geraniums beside her.",
         props="a small white espresso cup on a saucer, held in her hands from frame one",
         direction="a grandmother diagnosing your mornings like a doctor reading an X-ray",
         motive="thirty-four thousand mornings of evidence",
         goal="make the viewer recognise themselves and laugh",
         obstacle="she loses count at number three and has to bluff",
         tactic="she uses the cup as a pointer, eyes checking the lens after each flag",
         beats=[("Red flags in your morning", "a mock-grave face, the cup raised like a toast"),
                ("like a thief", "she hunches and darts guilty sideways glances"),
                ("nobody's chasing you", "she sits up straight, indignant"),
                ("The first face you talk to", "she taps her temple with a finger of the free hand, incredulous"),
                ("The neighbor, the cat", "a dismissive flick of the free hand"),
                ("Red flag number three", "she frowns, searching; the register breaks and she gives up with a shrug"),
                ("Green flag?", "eyebrows up, a sudden warm smile"),
                ("Now go open a window", "she points the cup up toward the sky above the alley")],
         centerpiece="THE GIVE-UP at number three",
         final="she sips the coffee, eyes on the lens over the rim",
         physics="the coffee surface trembling in the cup, the saucer clinking softly, cardigan sleeves shifting",
         mood="teasing, quick, warm",
         first_frame="sitting on the low stool by the blue door holding a small espresso cup and saucer, a mock-grave expression at the lens",
         split="nobody's chasing you."),
    dict(id="R6", fmt="C", loc="kitchen", light="morning", outfit="default", duration=10,
         cam=("propped", "a jar on the kitchen counter, at a 45-degree side angle to the table"),
         framing="45-degree medium shot. She sits at the table in the LOWER two-thirds of the frame; the upper third is calm white wall and tiles (text-safe).",
         props="the dented aluminium moka pot on a cork trivet on the table, and a small empty white cup on a saucer, both in place from frame one",
         action="she lifts the dented moka pot, pours coffee into the small cup with a little steam, sets the pot down, raises the cup and looks out of the window at the sea, then sets the cup down with both hands resting either side of it",
         loop="the last pose (hands resting either side of the cup, eyes on the window) is close to the first pose",
         direction="her morning coffee, unhurried",
         physics="a thin stream of dark coffee, rising steam, a faint clink of cup on saucer, the pot's dent catching the window light",
         mood="slow, golden, peaceful",
         first_frame="sitting at the kitchen table at a 45-degree angle, one hand reaching for the dented aluminium moka pot on a cork trivet, a small empty white cup on a saucer in front of her, the upper third calm white wall and blue-and-white tiles"),
    dict(id="R7", fmt="B", loc="doorstep", light="evening", outfit="doorstep",
         cam=("propped", "a terracotta pot on the doorstep step at a 45-degree angle; Giulia sits on the step just beside the lens"),
         framing="45-degree medium shot. She sits on the low stool; her eyeline goes to Giulia just beside the lens, never into it.",
         props=None,
         direction="telling Giulia the necklace story she has heard a hundred times, this time for the camera",
         motive="Salvatore; the pride of that day is still alive in her",
         goal="make Giulia and everyone see him walking up the steps",
         obstacle="the grief at the end, which she won't let turn sad",
         tactic="she performs the swordfish with her hands, then grows quiet; eyes on Giulia, never the lens",
         beats=[("My husband bought me this", "THE SIGNATURE: two fingertips tap the red coral beads twice; a proud glance at Giulia"),
                ("Salvatore", "the name said softly, a tiny pause"),
                ("a swordfish so big", "her arms spread wide, eyes wide"),
                ("like a... like a second boat", "she searches for the words and laughs at herself"),
                ("he comes up all the steps", "her fingers walk up an invisible staircase"),
                ("Red coral.", "she lifts the beads slightly between finger and thumb"),
                ("every morning he walked me down", "the register breaks: quieter, her eyes drop for a moment"),
                ("Now I walk myself", "chin up again, a small brave smile at Giulia"),
                ("I still say good morning to him", "a gentle shrug, eyes glistening but bright, no tears")],
         centerpiece="THE QUIET TURN on 'every morning he walked me down to the sea'",
         final="she looks down the alley toward the sea, then back at Giulia with a small nod",
         physics="the coral beads clicking softly between her fingers, the cardigan sleeve sliding up to show the anchor tattoo when she spreads her arms, swallows overhead",
         mood="proud, funny, then tender",
         first_frame="sitting on the low stool by the blue door in warm evening shade, grey cardigan over the housedress, looking to the side of the lens at someone off camera, fingertips resting on the red coral beads",
         split="with this in his pocket."),
    dict(id="R8", fmt="A", loc="doorstep", light="afternoon", outfit="default",
         cam=("selfie", "at full arm's length, a little too far away and slightly low, the way older people hold a phone"),
         framing="Selfie, a little wide: head and shoulders with the shady alley, the blue door and a bright strip of sun high on the wall behind her.",
         props=None,
         direction="defending the nap like a lawyer defending her whole town",
         motive="a lifetime of riposo; she can't believe it needs defending",
         goal="make the viewer take a forty-minute rest without guilt",
         obstacle="the heat; she is half-yawning herself",
         tactic="she mocks hustle culture with her free hand, eyes daring the lens to argue",
         beats=[("You call it lazy", "a pitying look at the lens"),
                ("Riposo", "she says it like a sacred word, eyes half-closing"),
                ("even the dogs lie down", "her free hand flops flat, demonstrating"),
                ("I'm not a cat", "mock offence, eyebrows up"),
                ("Forty minutes, and I have", "she sits up, energised, one finger raised"),
                ("a meeting about", "her face scrunches in confusion, then dismissal"),
                ("Lie down, amore", "softer, coaxing"),
                ("It always is", "a slow knowing nod")],
         centerpiece="THE CONFUSION on 'another meeting'",
         final="a small yawn she tries to hide, then a laugh",
         physics="front-camera wide distortion with her arm extended, the phone bobbing gently with her gestures",
         mood="lazy-warm, teasing",
         first_frame="a slightly-too-far selfie at arm's length, sitting on the stool in the shady alley in her white linen shirt, a pitying amused look at the lens",
         split="I'm not a cat."),
    dict(id="R9", fmt="A", loc="doorstep", light="evening", outfit="doorstep",
         cam=("companion", "at chest height, standing a step down the alley"),
         framing="Medium shot, she sits on the low stool by the blue door; the alley runs away behind her at frame right (Concetta's door is two doors down, off-frame).",
         props=None,
         direction="part two, now with a target: Concetta",
         motive="the rivalry is the spice of her life",
         goal="get the laugh on Concetta and close with the Giulia joke",
         obstacle="the Salvatore memory pulls at her mid-list",
         tactic="she counts on her fingers again and glances down the alley at Concetta's door",
         beats=[("Things I never do, part two", "two fingers up, a bright look at the lens"),
                ("I never say at my age", "a wagging finger"),
                ("at my age, at my age", "a whiny imitation, mouth pulled down"),
                ("she's a baby", "a dismissive flick toward the alley"),
                ("I never go to bed angry", "a softer face"),
                ("like the boats in a storm", "her two fists bump together like boats"),
                ("finished, basta", "a decisive flat-hand cut; the register is back to firm"),
                ("Except now", "she freezes, caught out, then laughs"),
                ("Giulia wants a good angle", "eyes up to Giulia, a mock-diva chin pose"),
                ("Part three when Concetta", "a sly glance down the alley")],
         centerpiece="THE MOCK-DIVA POSE",
         final="she holds the pose a second, then waves Giulia off",
         physics="the cardigan shifting with her gestures, slippers scuffing the stone, swallows overhead",
         mood="gossipy, mischievous",
         first_frame="sitting on the low stool by the blue door in evening shade, two fingers raised, a bright cheeky look at the lens",
         split="finished, basta."),
    dict(id="R10", fmt="A", loc="rocks", light="windy", outfit="swim",
         cam=("companion", "at chest height, standing braced against the wind one step away"),
         framing="Medium shot. She sits on the wet rock by the ladder; behind her the choppy grey-turquoise sea and small whitecaps.",
         props="the striped towel round her shoulders (flaps in the wind but stays on)",
         sfx="waves slapping the rocks, strong wind gusts buffeting the phone mic, a gull struggling in the wind",
         direction="a working lesson in sea sense on a rough day",
         motive="eighty-five years taught her to respect the sea",
         goal="show that clever beats brave",
         obstacle="the wind snatching at her words and her hair",
         tactic="she points at the waves as evidence, then turns to the lens to teach",
         beats=[("Today the sea is angry", "she points out at the choppy water, squinting into the wind"),
                ("I stay by the ladder", "she pats the ladder rail beside her"),
                ("the water comes up to here", "her hand flat at her chest"),
                ("I'm not stupid", "a tap of her temple, eyebrows up"),
                ("The sea doesn't care", "THE SIGNATURE: two fingertips tap the coral beads twice"),
                ("but it also doesn't care how brave", "the register breaks: firm, eyes hard on the lens"),
                ("you go with somebody", "a nod toward Giulia off-lens"),
                ("Ciao. See you tomorrow.", "she waves at the sea, dismissive and fond")],
         centerpiece="THE TURN from catchphrase to warning",
         final="she pulls the towel tighter and tilts her head to Giulia: let's go",
         physics="the wind tugging her wet hair and the towel, spray lifting off the rocks behind, the phone mic buffeted",
         mood="brisk, practical, fond",
         first_frame="sitting on the wet limestone by the metal ladder on a grey windy morning, choppy sea with small whitecaps behind, wet hair blowing, the striped towel round her shoulders, pointing out at the waves",
         split="I'm not stupid."),
    dict(id="R11", fmt="A", loc="kitchen", light="morning", outfit="default",
         cam=("propped", "the bowl of lemons on the table, framing her and the small window beside her"),
         framing="Medium shot. She sits at the table right beside the small window (closed at the start), a touch off-center.",
         props="the small kitchen window beside her, closed at the start; she opens it on the scripted beat",
         direction="a demonstration: day one is a window",
         motive="the simplest habit of her life, and the one people skip",
         goal="make it feel too easy not to try tomorrow",
         obstacle="she's selling something free; the ugly-car joke",
         tactic="she demonstrates, then turns to the lens like a teacher",
         beats=[("Day one.", "one finger up"),
                ("just a window", "she gestures to the window beside her"),
                ("you open it. Wide.", "she reaches over and pushes the window wide open; morning light floods her face"),
                ("afraid of the air", "a mocking little cringe"),
                ("light on the face", "she closes her eyes and tilts her face to the light for a beat"),
                ("the neighbor's ugly car", "a wicked grin"),
                ("Day two is... no", "she starts to tell, then zips her lips"),
                ("All thirty mornings", "a small nod at the lens")],
         centerpiece="THE WINDOW OPENING, light flooding her face while the old phone's exposure catches up a beat late",
         final="she breathes in the air, eyes closed, a contented smile",
         physics="the window swinging open on old hinges, the auto-exposure correcting a beat late as light floods in, the curtain edge lifting",
         mood="bright, simple, inviting",
         first_frame="sitting at the kitchen table right beside the small closed window, one finger raised, morning light glowing around the window frame",
         split="light on the face."),
    dict(id="R12", fmt="A", loc="kitchen", light="morning", outfit="sunday",
         cam=("propped", "the dented moka pot standing on the table in front of her"),
         framing="Medium close-up, chest-up, the moka pot's rim soft in the near foreground.",
         props=None,
         direction="part three, short because Giulia says so",
         motive="she loves the series and hates being told it's too long",
         goal="two items, then win the argument with Giulia",
         obstacle="she trips over her own television metaphor",
         tactic="she counts on her fingers and argues with herself mid-sentence",
         beats=[("Things I never do, part three", "three fingers up"),
                ("Giulia says my videos are too long", "an eye-roll toward Giulia off-lens"),
                ("in front of the television", "a stern face"),
                ("no, wait, you do watch it", "she stops herself, confused, then delighted by the correction"),
                ("you look at your plate", "she points down at an imaginary plate"),
                ("I never miss Sunday lunch", "a warm softening"),
                ("Especially then", "a knowing look"),
                ("Giulia, it's short enough?", "she turns to Giulia off-lens, hopeful"),
                ("She says no", "back to the lens, deadpan betrayal")],
         centerpiece="THE DEADPAN 'She says no'",
         final="she throws up her hands",
         physics="the polka-dot dress fabric moving with her gestures, the moka pot rocking minutely as the phone settles against it",
         mood="playful, Sunday-warm",
         first_frame="sitting at the kitchen table in her navy dress with small white dots and a black cardigan, three fingers raised, the dented moka pot in the near foreground",
         split="that's the whole point."),
    dict(id="R13", fmt="A", loc="rocks", light="october", outfit="swim",
         cam=("companion", "at chest height, standing on the rock one step away"),
         framing="Medium shot, she sits on the rock by the ladder, the calm empty bay behind her.",
         props="the striped towel round her shoulders",
         direction="October: the sea is hers again",
         motive="she has watched eighty-five summers of tourists come and go",
         goal="make the viewer go outside this week",
         obstacle="Giulia filming her feet",
         tactic="she shares the secret of October water like insider knowledge",
         beats=[("October.", "a satisfied look at the empty bay"),
                ("the sea is mine again", "one arm opens toward the sea"),
                ("the hard part is coming out", "a theatrical shiver inside the towel"),
                ("Coming out.", "a firm nod"),
                ("Eighty-five Octobers", "a proud smile"),
                ("Except Giulia.", "her eyes snap up to Giulia, a swat of the hand"),
                ("go outside this week", "she leans toward the lens, serious"),
                ("one sad tree", "a droopy-tree mime with her hand, then a laugh")],
         centerpiece="THE SAD TREE",
         final="she pulls the towel snug and looks out to sea",
         physics="water dripping from her hair, the towel pulled tight, gooseflesh on her forearms",
         mood="content, autumn-soft, cheeky",
         first_frame="sitting on the limestone by the ladder on a soft autumn morning, wet hair, the striped towel round her shoulders, looking at the calm empty bay with a satisfied smile",
         split="Coming out."),
    dict(id="R14", fmt="B", loc="kitchen", light="morning", outfit="default",
         cam=("propped", "the bowl of lemons at a 45-degree angle; Giulia sits at the table just beside the lens"),
         framing="45-degree medium shot. Her eyeline goes to Giulia beside the lens, never into it.",
         props=None,
         direction="repeating her morning sermon, aware Giulia never listens",
         motive="she wants Giulia to have what she had",
         goal="for once, make it stick",
         obstacle="Giulia's eye-roll off camera, and her own exasperation",
         tactic="she lectures Giulia directly, then wins with the last line",
         beats=[("Every morning I tell her", "a glance at Giulia, fond exasperation"),
                ("It's decided at seven", "she taps the table with one finger, emphatic"),
                ("The telephone or the window", "one hand weighs each option like a scale"),
                ("like a thief", "a hunched guilty mime"),
                ("that's so old-fashioned", "a whiny teenage imitation"),
                ("Old-fashioned and ninety-four", "chin up, proud: the register breaks"),
                ("in a little book", "she shapes a small book with her hands"),
                ("you're buying one", "a triumphant point at Giulia")],
         centerpiece="THE PROUD CHIN on 'Old-fashioned and ninety-four'",
         final="she sits back, arms folded, victorious",
         physics="linen sleeves sliding, the tablecloth wrinkling under her tapping finger",
         mood="fond exasperation, then victory",
         first_frame="sitting at the kitchen table, looking to the side of the lens at someone off camera with fond exasperation, the bowl of lemons in the near foreground",
         split="like a thief."),
    dict(id="R15", fmt="A", loc="doorstep", light="evening", outfit="doorstep",
         cam=("companion", "at chest height, standing a step down the alley"),
         framing="Medium shot, she sits on the low stool, the alley running away at frame right toward Concetta's door (off-frame).",
         props=None,
         direction="spilling the gossip about her rival",
         motive="Concetta copying her is the best compliment and the worst insult",
         goal="the viewer laughs and wants what Concetta got",
         obstacle="she has to stay outraged and proud at the same time",
         tactic="she whispers like it's a secret, glancing at Concetta's door",
         beats=[("Concetta, two doors down", "a nod down the alley, voice lowered"),
                ("Secretly.", "a finger to her lips"),
                ("like a statue", "she freezes, rigid, miming a glass held at a window"),
                ("she walks to the bakery herself", "two fingers walk along her knee"),
                ("Her new mornings!", "outrage, both hands up"),
                ("She says it was her idea", "a scandalised gasp"),
                ("Madonna.", "eyes to the sky"),
                ("tell her Rosa sent you", "a wicked grin into the lens")],
         centerpiece="THE STATUE mime",
         final="she glances toward Concetta's door and waves sweetly",
         physics="the cardigan shifting, the stool creaking, evening swallows",
         mood="gossipy, outraged, delighted",
         first_frame="sitting on the stool by the blue door in evening shade, leaning toward the lens conspiratorially, glancing down the alley",
         split="like a statue."),
]

# ---------------------------------------------------------------- RAY
V["ray"] = [
    dict(id="Y1", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy, a little below his eye level"),
         framing="Near-frontal medium close-up, chest-up. He sits at the small Formica table, a touch off-center; the net curtains and pale green cupboards soft behind him.",
         props="the open spiral notebook (illegible pencil columns), the old calculator and a mug of tea on the table (static until the final beat)",
         direction="a plumber's home visit, but for your money",
         motive="forty-six years of finding leaks people swore weren't there",
         goal="the viewer realises they have the leak",
         obstacle="he refuses to raise his voice, so it has to land deadpan",
         tactic="he diagnoses calmly, pauses, and lets the viewer convict themselves; eyes check the lens after each flag",
         beats=[("Red flags your money's got a leak", "a level look at the lens, almost bored"),
                ("From a plumber.", "a tiny nod, as if showing his ID"),
                ("that's a horror film", "deadpan, one eyebrow lifts"),
                ("Your subscriptions have got subscriptions", "a slow blink"),
                ("no, this one's not a flag", "he stops himself and leans in: the register breaks"),
                ("Not roughly. Not at all.", "a small headshake"),
                ("It's just in the wall", "he taps the wall beside the table twice with a knuckle")],
         centerpiece="THE KNUCKLE-TAP on the wall",
         final="he picks up the mug and sips, eyes on the lens over the rim",
         physics="the cosy's wool flattening where the phone leans, steam curling off the mug, the moustache moving with his words",
         mood="dry, deadpan, quietly devastating",
         first_frame="sitting at the small Formica kitchen table, forearms on the table, a mug of tea by his hand, an open notebook and old calculator beside it, a level deadpan look into the lens, net curtains behind",
         split="Your subscriptions have got subscriptions."),
    dict(id="Y2", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up, the mug held at chest height.",
         props="a mug of tea held in both hands from frame one",
         direction="an inventory of a lifetime of not paying",
         motive="each item is a small victory he's proud of",
         goal="make the viewer laugh, then think about the credit card line",
         obstacle="the haircut confession embarrasses him slightly",
         tactic="he counts items on his fingers around the mug, with deadpan pauses",
         beats=[("Things I have never paid for", "a sip of tea, then a level look"),
                ("A car wash.", "one finger lifts off the mug"),
                ("I've got a Sunday", "a slight smile under the moustache"),
                ("since the Victorians", "a tiny proud nod"),
                ("A haircut. Well...", "he lifts his cap a centimetre and settles it back exactly as it was; sheepish, the register breaks"),
                ("With the chicken scissors", "a resigned blink"),
                ("Not once.", "serious, eyes steady on the lens"),
                ("Part two when Maureen lets me", "a glance off toward the door, Maureen's domain")],
         centerpiece="THE CAP LIFT on the haircut",
         final="he sips the tea again",
         physics="the cap lifting and resettling over real hair, the mug steaming, jumper wool creasing",
         mood="dry, proud, a little sheepish",
         first_frame="sitting at the kitchen table holding a mug of tea in both hands, a level deadpan look into the lens, net curtains behind",
         split="since the Victorians."),
    dict(id="Y3", fmt="A", loc="shed", light="day", outfit="shed",
         cam=("propped", "a jam jar of screws on the workbench"),
         framing="Medium close-up. He sits on a stool at the workbench, chest-up, the pegboard of tools soft behind him.",
         props="a flat-head screwdriver lying on the bench from frame one (picked up only in the final beat)",
         direction="an old man unimpressed by a 'new' trend",
         motive="he's done this since 1983 without a name for it",
         goal="make 'no' feel easy",
         obstacle="staying deadpan while it's funny",
         tactic="he plays both sides of the conversation; each 'No.' lands like a flat stone",
         beats=[("You lot call it loud budgeting", "a slight squint of disbelief"),
                ("We called it no.", "a flat, final look"),
                ("it's forty quid. No.", "a tiny headshake"),
                ("it's got more telly", "a baffled frown"),
                ("That's the whole system. No.", "he spreads his hands: that's it"),
                ("You don't need a hashtag", "a dry blink"),
                ("people stop asking", "a small satisfied nod; the register softens"),
                ("Best money I never spent", "the faintest smile under the moustache")],
         centerpiece="THE FLAT 'No.'",
         final="he picks up the screwdriver and inspects the tip",
         physics="the jam jars catching the window light, the darned elbow patch visible as he gestures, the bench creaking",
         mood="deadpan, wry",
         first_frame="sitting on a stool at the shed workbench in an old grey jumper with a darned elbow, a slight squint of disbelief at the lens, jam jars of screws and a pegboard of tools behind",
         split="That's the whole system. No."),
    dict(id="Y4", fmt="B", loc="kitchen", light="sunday", outfit="sunday",
         cam=("propped", "the brown teapot at a 45-degree angle; Kelly sits at the table just beside the lens"),
         framing="45-degree medium shot. His eyeline goes to Kelly beside the lens, never into it.",
         props=None,
         direction="Kelly asks the big question and he finds the answer boring",
         motive="he's proud but allergic to showing off",
         goal="make Kelly understand it was ordinary",
         obstacle="the number impresses people, and he dislikes that",
         tactic="he underplays everything and gives Maureen the credit, eyes on Kelly",
         beats=[("Nineteen seventy-nine", "eyes up to the ceiling, remembering"),
                ("We did it in seventeen", "a small shrug"),
                ("Boring, love.", "a fond look at Kelly"),
                ("One car, and it was old", "one finger"),
                ("we lived on the old wage", "he taps the table with a fingertip, steady"),
                ("Your gran's idea", "he nods toward the door; the register breaks, warm"),
                ("I just wrote it down", "a small modest gesture at the notebook"),
                ("Boring's underrated", "the faintest smile")],
         centerpiece="THE CREDIT TO MAUREEN",
         final="he raises his eyebrows at Kelly: next question",
         physics="the checked shirt collar moving, his fingertip tapping the Formica",
         mood="modest, warm, dry",
         first_frame="sitting at the kitchen table in a navy V-neck over a blue-and-white checked shirt, looking to the side of the lens at someone off camera, eyes slightly up, remembering",
         split="It's all boring."),
    dict(id="Y5", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up, the notebook held at chest height.",
         props="an old spiral notebook held open in his hands from frame one (handwriting illegible); the reading glasses start hooked in his collar",
         direction="reading an old entry like a court record",
         motive="the notebooks are his life's evidence",
         goal="the viewer recognises boredom-spending",
         obstacle="he still regrets that pasty",
         tactic="he reads, peers at the lens over the glasses, deadpans",
         beats=[("March, nineteen eighty-seven", "he reads from the notebook, a finger on the line"),
                ("On a pasty I didn't even want", "a slow look up at the lens"),
                ("I've written next to it", "THE SIGNATURE: he unhooks the reading glasses from his collar, puts them on and peers at the page"),
                ("hungry? No. Bored.", "he reads it flatly, then looks over the glasses at the lens"),
                ("it's boredom", "a small nod"),
                ("with your card saved in it", "a raised eyebrow"),
                ("I can still taste it", "a faint grimace under the moustache"),
                ("It wasn't even a good pasty", "deadpan disgust: the punchline")],
         centerpiece="THE SIGNATURE and the over-the-glasses look",
         final="he closes the notebook with a soft pat",
         physics="old paper pages lifting slightly, the glasses' arms unfolding, illegible pencil marks",
         mood="deadpan, rueful",
         first_frame="sitting at the kitchen table holding an old spiral notebook open, a finger on a line, the reading glasses still hooked in his collar, reading, the teapot in the near foreground",
         split="still the best lesson in this whole notebook."),
    dict(id="Y6", fmt="A", loc="van", light="day", outfit="van",
         cam=("mounted", "on the dashboard in front of the passenger seat, angled at the driver's seat"),
         framing="Medium close-up. He sits in the driver's seat turned slightly toward the phone, one hand on the wheel; the rainy windscreen and the blurred terraced street beside him.",
         props=None,
         direction="defending an old van like an old friend",
         motive="she's paid for and she has never let him down",
         goal="make 'paid for' feel prettier than new",
         obstacle="the heater joke, and an affection he won't admit",
         tactic="he pats the van and deadpans the numbers",
         beats=[("My van is twenty-two years old", "he pats the steering wheel"),
                ("When she stops.", "a flat look"),
                ("a hundred and ninety-one thousand", "a slow proud nod"),
                ("The heater only works on full", "a tiny wince"),
                ("I'm warm.", "deadpan"),
                ("three hundred a month?", "eyebrows up, incredulous"),
                ("She's not pretty. She's paid for.", "he pats the dashboard; the register warms"),
                ("the prettiest thing", "the faintest smile")],
         centerpiece="THE DASHBOARD PAT",
         final="he looks out at the rain",
         physics="raindrops sliding down the windscreen, the fabric seat compressing, the cab rocking slightly when he shifts",
         mood="deadpan, fond",
         first_frame="sitting in the driver's seat of the old van's cab, jacket zipped up, one hand on the steering wheel, turned slightly toward the lens, rain on the windscreen",
         split="I'm warm."),
    dict(id="Y7", fmt="A", loc="van", light="day", outfit="default",
         cam=("mounted", "on the dashboard in front of the passenger seat, angled at the driver's seat"),
         framing="Medium close-up, he sits in the driver's seat, turned toward the phone.",
         props=None,
         direction="describing a mysterious neighbour who is obviously himself",
         motive="the quiet pride of a man nobody would guess",
         goal="the reveal lands without him saying it",
         obstacle="he mustn't smirk too early",
         tactic="he stays deadpan and pauses; one sideways glance at the end",
         beats=[("The richest man on my street", "a level look into the lens"),
                ("Same cap since", "he touches the brim of his cap: a tiny tell"),
                ("hides them from him", "a slight eyebrow"),
                ("House paid off at forty-one", "a small nod"),
                ("Nobody on the street knows", "a glance out of the side window at the street"),
                ("a face like a wet weekend", "deadpan"),
                ("I'm not saying who it is", "he holds back a smile"),
                ("Rich is quiet.", "a quiet steady look, then the faintest smile under the moustache")],
         centerpiece="THE CAP TOUCH and the final look",
         final="he settles the cap brim and looks out at the rain",
         physics="rain sliding, the cab's micro-movement, the cap brim",
         mood="dry, sly, quiet",
         first_frame="sitting in the driver's seat, navy work jacket open over the cream jumper, a level deadpan look into the lens, rain on the windscreen",
         split="Nobody on the street knows."),
    dict(id="Y8", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "a round biscuit tin on the kitchen table"),
         framing="Medium close-up, he leans slightly toward the lens over the table; the tin's rim soft in the near foreground.",
         props=None,
         direction="talking to his younger self in the viewer",
         motive="January 1983 still stings",
         goal="make one viewer buy a notebook and look",
         obstacle="the shame he's admitting to",
         tactic="plain-spoken, leaning in, eyes steady on the lens",
         beats=[("If you're twenty-five and skint", "he leans in slightly, kind"),
                ("I was skint.", "a small nod: a confession"),
                ("A plumber!", "a dry disbelieving look, the faint chuckle"),
                ("So I bought a notebook.", "finger and thumb show something tiny"),
                ("I just looked", "palms flat on the table"),
                ("They want the plan", "a small headshake"),
                ("Look first, love.", "softer, eyes kind"),
                ("Then it stops hurting", "a slow nod")],
         centerpiece="THE CONFESSION 'I was skint'",
         final="he sits back, arms folded",
         physics="the biscuit tin lid catching the window light, his palms on the Formica",
         mood="plain, kind, honest",
         first_frame="sitting at the kitchen table, leaning slightly toward the lens with a kind level look, a round biscuit tin in the near foreground",
         split="A plumber!"),
    dict(id="Y9", fmt="A", loc="kitchen", light="sunday", outfit="sunday",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up.",
         props="a mug of tea on the table by his hand (lifted only in the final beat)",
         direction="part two, Maureen-approved",
         motive="he loves the bit",
         goal="land 'I am the warranty'",
         obstacle="the gym item draws arguments",
         tactic="he re-enacts the shop conversation, deadpan",
         beats=[("Maureen says I'm allowed", "a glance off toward the door"),
                ("An extended warranty", "one finger"),
                ("lovely lad", "a generous nod"),
                ("I am the warranty", "he taps his own chest twice: the punchline, deadpan"),
                ("people argue with me about", "a weary blink"),
                ("a gym.", "eyebrows up"),
                ("I've got stairs", "he points up at the ceiling"),
                ("wants the shed moved again", "a resigned look toward the window")],
         centerpiece="THE CHEST TAP 'I am the warranty'",
         final="he lifts the mug and sips",
         physics="the checked shirt collar, the mug steaming",
         mood="deadpan, playful",
         first_frame="sitting at the kitchen table in a navy V-neck over a checked shirt, glancing to the side toward a door, a mug of tea by his hand",
         split="I am the warranty."),
    dict(id="Y10", fmt="C", loc="kitchen", light="sunday", outfit="sunday", duration=10,
         cam=("propped", "the biscuit tin at a 45-degree side angle"),
         framing="45-degree medium shot. He sits at the table in the LOWER two-thirds of the frame; the upper third is the calm net curtains and cupboards (text-safe).",
         props="a closed spiral notebook, a pencil, the brown teapot and a mug on the table from frame one; the reading glasses hooked in his collar",
         action="he unhooks the reading glasses from his collar, puts them on, opens the notebook to a fresh page, picks up the pencil and pauses with it just above the page",
         loop="the last pose (pencil poised above the page, eyes down) sits close to the first pose (hands on the closed notebook, eyes down)",
         direction="the weekly ritual, unhurried",
         physics="glasses' arms unfolding, notebook pages turning with a soft paper sound, steam from the mug",
         mood="calm, ritual, Sunday-quiet",
         first_frame="sitting at the kitchen table on a late Sunday afternoon at a 45-degree angle, hands resting on a closed spiral notebook with a pencil beside it, a brown teapot and a mug, the reading glasses hooked in his collar, the upper third calm net curtains and pale green cupboards"),
    dict(id="Y11", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up, the open notebook on the table in front of him.",
         props="an open spiral notebook and a pencil on the table from frame one (handwriting illegible); the reading glasses start hooked in his collar",
         direction="teaching the one-sitting method like training an apprentice",
         motive="it's how he has found every leak for forty-six years",
         goal="make the viewer book the evening",
         obstacle="it sounds like homework; he has to make it sound like common sense",
         tactic="he demonstrates with the pencil on the notebook and checks the lens after the key question",
         beats=[("When I find a leak", "he taps the pencil on the table"),
                ("I turn the water off", "a stopcock-turning motion with his hand"),
                ("Same with money.", "a level look"),
                ("One sitting, kettle on.", "a nod toward the kettle off-frame"),
                ("would I buy this again today?", "THE SIGNATURE: the glasses go on; he peers at the lens over them"),
                ("Not, do I need it.", "a small headshake"),
                ("a few you forgot you had", "the faint chuckle"),
                ("It's in my bio", "a modest nod")],
         centerpiece="THE QUESTION with the over-the-glasses look",
         final="he writes one small tick on the page",
         physics="the pencil tapping, paper pages lifting, the glasses' arms unfolding",
         mood="calm, practical, kind",
         first_frame="sitting at the kitchen table with an open notebook and a pencil in front of him, the reading glasses hooked in his collar, tapping the pencil, a level look at the lens",
         split="Same with money."),
    dict(id="Y12", fmt="A", loc="shed", light="day", outfit="shed",
         cam=("propped", "a jam jar of screws on the workbench"),
         framing="Medium shot. He sits on a stool at the workbench; an old metal bucket by his boot at the bottom of frame.",
         props="an old metal bucket on the floor by his boot from frame one",
         direction="explaining a rule he invented and is proud of",
         motive="the pressure-washer saga",
         goal="make the thirty-day list sound like freedom, not denial",
         obstacle="the pressure washer embarrassment",
         tactic="he points to the door, counts days on his fingers, and ends deadpan",
         beats=[("Ray's rule.", "a level look"),
                ("goes on a list", "he mimes writing in the air"),
                ("on the shed door", "he points off-frame to the door"),
                ("no guilt, no fuss", "a flat-hand smoothing gesture"),
                ("day nine, day ten", "counting on his fingers, then trailing off"),
                ("a pressure washer", "eyebrows up, a guilty look"),
                ("Still got a bucket.", "deadpan, then the faint chuckle")],
         centerpiece="THE PRESSURE WASHER confession",
         final="he glances down at the bucket by his boot",
         physics="the jam jars catching window light, rain on the roof, the stool creaking",
         mood="dry, amused",
         first_frame="sitting on a stool at the shed workbench in an old grey jumper, an old metal bucket by his boot, a level look at the lens",
         split="no guilt, no fuss."),
    dict(id="Y13", fmt="A", loc="kitchen", light="evening", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up, the notebook held at chest height.",
         props="an old spiral notebook held open in his hands from frame one (handwriting illegible, one tiny pencil star doodle in the margin); the reading glasses start hooked in his collar",
         direction="reading two Christmases side by side",
         motive="Gary's bike was a proud moment; the year before was a shame",
         goal="the viewer feels the difference between saved-for and borrowed",
         obstacle="the emotion about Gary that he won't show",
         tactic="he reads flatly, shows the star, and lets the contrast land quietly",
         beats=[("December, nineteen ninety-one", "he reads from the page"),
                ("Bike for our Gary", "a small fond smile under the moustache"),
                ("ten pound a month", "he taps the page"),
                ("I've drawn a little star", "THE SIGNATURE: the glasses go on, and he tilts the notebook toward the lens (the star is a tiny pencil doodle; all handwriting illegible)"),
                ("till it fell to bits", "a warm chuckle"),
                ("on the never-never", "his face hardens slightly: the register breaks"),
                ("March!", "dry disbelief"),
                ("Same boy. Different January.", "a quiet steady look over the glasses")],
         centerpiece="THE STAR shown to the lens",
         final="he closes the notebook gently",
         physics="pages turning, the warm bulb glinting on the glasses",
         mood="fond, quiet, wise",
         first_frame="sitting at the kitchen table in the evening under the warm ceiling bulb, holding an open spiral notebook, the reading glasses in his collar, a small fond smile",
         split="He rode that bike till it fell to bits."),
    dict(id="Y14", fmt="B", loc="kitchen", light="sunday", outfit="sunday",
         cam=("propped", "the brown teapot at a 45-degree angle; Kelly sits at the table just beside the lens"),
         framing="45-degree medium shot. His eyeline goes to Kelly beside the lens, never into it.",
         props="a mug of tea in his hand from frame one",
         direction="explaining the ritual to his granddaughter, who should be doing it",
         motive="he wants Kelly never to have a January 1983",
         goal="make it sound small enough to start",
         obstacle="Maureen's role: he wants the credit, but she checks it",
         tactic="gentle and teaching; he gestures at the notebook, eyes on Kelly",
         beats=[("Sunday Sums.", "a fond look at Kelly"),
                ("a brew and the notebook", "he lifts the mug slightly"),
                ("Last week's money", "one hand to the left, then the other to the right: two piles"),
                ("well, I do everything else", "a self-correcting smirk"),
                ("but she checks it", "a glance toward the door"),
                ("a big monster", "hands wide"),
                ("It's a drip you never look at", "finger and thumb close together: tiny"),
                ("It's in my bio", "a nod")],
         centerpiece="THE MONSTER-VERSUS-DRIP gesture",
         final="he sips the tea",
         physics="steam from the mug, the checked shirt collar",
         mood="gentle, fond, practical",
         first_frame="sitting at the kitchen table in a navy V-neck over a checked shirt, a mug of tea in hand, looking to the side of the lens at someone off camera with a fond look",
         split="but she checks it."),
    dict(id="Y15", fmt="A", loc="kitchen", light="day", outfit="default",
         cam=("propped", "the brown teapot under its knitted cosy"),
         framing="Medium close-up, chest-up.",
         props="the reading glasses start hooked in his collar",
         direction="a message to his twenty-seven-year-old self",
         motive="he remembers the embarrassment more than the debt",
         goal="take the shame away from the viewer",
         obstacle="his own emotion, and the math/maths slip",
         tactic="he speaks to the lens as if it were young Ray, with one small self-correction joke",
         beats=[("If I could go back", "his eyes drift off, remembering"),
                ("I'd say, lad", "eyes back to the lens, gentle"),
                ("the forty little things", "his fingers count tiny things"),
                ("stop being embarrassed", "firm and kind"),
                ("it's a math problem. Maths.", "he corrects himself with a tiny wince: the register breaks, comic"),
                ("Then I'd give him a notebook", "THE SIGNATURE: the glasses go on"),
                ("He'd have probably lost it", "the faint chuckle")],
         centerpiece="THE CORRECTION 'Maths.'",
         final="he looks down at the table, then back up with a small nod",
         physics="the glasses' arms unfolding, the moustache moving with his words",
         mood="tender, dry, wise",
         first_frame="sitting at the kitchen table, eyes drifting off to the side, remembering, the teapot in the near foreground, the reading glasses hooked in his collar",
         split="That's where it goes."),
]

# ---------------------------------------------------------------- LOU
V["lou"] = [
    dict(id="L1", fmt="A", loc="armchair", light="afternoon", outfit="default",
         cam=("propped", "a short stack of hardback books on the side table, at a 45-degree angle"),
         framing="45-degree medium shot, chest-up. He sits in the brown leather armchair; the lamp and the wall photos are soft behind him.",
         props=None,
         direction="the first rule, delivered like an old judge",
         motive="he courted Angie properly, and it worked for sixty-five years",
         goal="the viewer stops answering 11pm 'hey's",
         obstacle="he mixes up Monday and Tuesday",
         tactic="one finger raised like a gavel; he corrects himself, then lands 'Hey is not a question'",
         beats=[("Lou's rule number one", "one finger up, eyes twinkling"),
                ("you're not a plan", "a slow headshake"),
                ("You're the leftovers", "a small apologetic shrug"),
                ("no, a Tuesday", "he corrects himself, eyes up, remembering, a chuckle"),
                ("like a court date", "a mock-official nod"),
                ("with a hey", "a disdainful little wave"),
                ("Hey is not a question", "THE SIGNATURE: he touches the gold wedding band on the chain; steady eyes on the lens"),
                ("Rule number two next week", "a twinkle, one finger up again")],
         centerpiece="THE SIGNATURE on 'Hey is not a question'",
         final="he settles back into the armchair",
         physics="the leather creaking, the chain glinting, cardigan buttons catching the light",
         mood="warm authority, twinkly",
         first_frame="sitting in the worn brown leather armchair at a 45-degree angle, chest-up, one finger raised, twinkling eyes on the lens, warm late-afternoon light",
         split="You're the leftovers."),
    dict(id="L2", fmt="B", loc="lunch", light="day", outfit="sunday",
         cam=("companion", "across the table at chest height, sitting"),
         framing="Medium shot across the table. His eyeline goes to Nicky just beside the lens, never into it. The red sauce and rigatoni are soft in the foreground.",
         props="a fork held in his right hand from frame one",
         direction="grandpa decoding a modern word at the lunch table",
         motive="he hates seeing his grandkids hurt by vague people",
         goal="Nicky, and the viewer, will ask the question",
         obstacle="he genuinely mishears the word",
         tactic="he taps his hearing aid, translates the word into 1955, and delivers a verdict, eyes on Nicky",
         beats=[("A what-ship?", "COMIC MOVE: he taps his hearing aid and leans toward Nicky"),
                ("A situation-ship. Okay.", "a slow nod, processing"),
                ("you go to the sister's birthday", "he counts on his fingers, puzzled"),
                ("nobody's allowed to ask", "eyebrows up, incredulous"),
                ("We called it, he's not serious", "a flat, knowing look"),
                ("Took two seconds to say", "a chuckle"),
                ("it already hurts", "the register breaks: quiet and kind, leaning in"),
                ("The answer's free", "he points the fork gently at Nicky")],
         centerpiece="THE QUIET LEAN on 'it already hurts'",
         final="he goes back to his rigatoni",
         physics="the paper napkin in his collar, the fork tines catching light, family murmur off-frame",
         mood="funny, then tender",
         first_frame="sitting at the Sunday lunch table, a white paper napkin tucked into his collar, a fork in hand, leaning toward someone across the table just beside the lens with a puzzled frown",
         split="nobody's allowed to ask."),
    dict(id="L3", fmt="A", loc="stoop", light="golden", outfit="stoop",
         cam=("companion", "at his eye level, sitting two steps below him"),
         framing="Medium shot. He sits on the top step, a touch off-center; the iron handrail and the potted chrysanthemum are beside him.",
         props=None,
         direction="the origin story, told on the stoop",
         motive="Angie, the best decision of his life",
         goal="the viewer learns 'a day and a time'",
         obstacle="the ache of telling it without her",
         tactic="he tells it like a joke until the last line",
         beats=[("eleven cents in my pocket", "he pats his coat pocket"),
                ("A dime and a penny", "two fingers, then one"),
                ("she works at the bakery", "a nod down the street"),
                ("My mother thought I was sick", "a laugh"),
                ("Angie, Saturday, two o'clock", "he sits up straighter, playing his younger self"),
                ("One soda, two straws", "two fingers held up like straws"),
                ("I left the penny for a tip", "a proud chuckle"),
                ("Sixty-five years, kid", "THE SIGNATURE: he touches the ring on the chain; quieter"),
                ("a day and a time", "a steady look")],
         centerpiece="THE SIGNATURE on 'Sixty-five years, kid'",
         final="he looks down the street with a small smile",
         physics="leaves skittering on the steps, the camel coat folding, long golden shadows",
         mood="charming, then quietly moving",
         first_frame="sitting on the top brownstone step at golden hour in a camel car coat over a moss-green cardigan, patting his coat pocket, a twinkly grin at the lens",
         split="My mother thought I was sick."),
    dict(id="L4", fmt="A", loc="armchair", light="afternoon", outfit="default",
         cam=("propped", "a short stack of hardback books on the side table, at a 45-degree angle"),
         framing="45-degree medium shot; the framed wedding photo on the side table is visible from the side (no faces).",
         props=None,
         direction="red flags passed down from Angie",
         motive="Angie's wisdom deserves an audience",
         goal="two flags and a green one, cleanly",
         obstacle="admitting he was wrong four thousand times",
         tactic="he counts on his fingers, quotes Angie in a softer voice, and makes a sheepish correction",
         beats=[("Red flags from nineteen fifty-five", "a mock-serious face"),
                ("rude to the waiter", "one finger"),
                ("Angie used to say", "his eyes soften, a glance at the framed photo"),
                ("They're never wrong. Never!", "a scoff"),
                ("I was wrong maybe four thousand times", "a hand up, guilty"),
                ("well, most times", "a sheepish correction, a chuckle"),
                ("Green flag?", "he brightens"),
                ("Not one day.", "a steady, quiet look")],
         centerpiece="THE SHEEPISH 'well, most times'",
         final="a small nod at the framed photo",
         physics="the leather creaking, the chain glinting",
         mood="wry, warm",
         first_frame="sitting in the leather armchair with a mock-serious face at the lens, one finger raised, the framed wedding photo on the side table seen from the side",
         split="well, most times."),
    dict(id="L5", fmt="A", loc="lunch", light="day", outfit="sunday",
         cam=("companion", "across the table at chest height, sitting"),
         framing="Medium shot across the table, he speaks to the lens; plates and the sauce pot soft in the foreground.",
         props="a piece of crusty bread on his plate (picked up only in the final beat)",
         direction="upgrading a slogan for his grandkids",
         motive="he called Angie every night at seven",
         goal="brand the viewer with 'Don't text. Call.'",
         obstacle="Nicky's generation's fear of the phone",
         tactic="he fixes the phrase like an editor, then does the cord gesture",
         beats=[("If he wanted to, he would", "he repeats it slowly, testing it"),
                ("It's close.", "a so-so hand wobble"),
                ("Not text. Call.", "he taps the table on each word"),
                ("from the bathroom", "a disgusted little face"),
                ("you have to mean it", "he restarts, leaning in"),
                ("with the cord this long", "he holds his hands apart, measuring the cord"),
                ("Don't text, sweetheart. Call.", "THE SIGNATURE: he touches the ring on the chain; steady eyes on the lens")],
         centerpiece="THE SIGNATURE on the catchphrase",
         final="he picks up the bread",
         physics="the napkin in his collar, the cutlery, family murmur off-frame",
         mood="warm, firm, charming",
         first_frame="sitting at the Sunday lunch table in a cream cable-knit cardigan with a napkin tucked into his collar, looking at the lens about to speak, red sauce and rigatoni on the table",
         split="Not text. Call."),
    dict(id="L6", fmt="B", loc="lunch", light="day", outfit="sunday",
         cam=("companion", "across the table at chest height, sitting"),
         framing="Medium shot across the table. His eyeline goes to Nicky just beside the lens, never into it.",
         props=None,
         direction="grandpa asked about his 'rizz'",
         motive="he was a charmer, and he knows it",
         goal="make 'showing up and shutting up' the answer",
         obstacle="he mishears 'rizz' as 'rice'",
         tactic="he taps his hearing aid, then shares a proud memory, eyes on Nicky",
         beats=[("My what?", "COMIC MOVE: he taps his hearing aid and leans toward Nicky"),
                ("Like rice?", "he points at the bowl of rigatoni"),
                ("Oh. Rizz.", "a dawning, amused look"),
                ("With my shoes shined", "he brushes his cardigan front proudly"),
                ("I had hair then", "a rueful pat of his thin hair"),
                ("in case of wind", "a comb mime at the back pocket"),
                ("Showing up and shutting up", "a satisfied nod"),
                ("for that and the dancing", "a little shoulder shimmy, a chuckle")],
         centerpiece="THE SHIMMY",
         final="he laughs and waves Nicky off",
         physics="the napkin in his collar, the cardigan cables shifting",
         mood="playful, proud",
         first_frame="sitting at the Sunday lunch table with a napkin in his collar, leaning toward someone across the table just beside the lens, a hand cupped near his hearing aid",
         split="in case of wind."),
    dict(id="L7", fmt="A", loc="stoop", light="golden", outfit="stoop",
         cam=("selfie", "close to his face in both hands, a little too close and slightly below his chin"),
         framing="A too-close selfie: his face fills much of the frame, the stoop steps and golden street tilting behind.",
         props=None,
         direction="genuinely upset about ghosting",
         motive="thirty-eight years of announcing his stops",
         goal="the viewer sends the one sentence",
         obstacle="he isn't good with the phone; the selfie wobbles",
         tactic="he uses bus-driver authority and the depot line",
         beats=[("Ghosting.", "he squints into the too-close phone"),
                ("I'm still upset", "a wounded look"),
                ("you just... disappear?", "eyebrows up, baffled"),
                ("I drove a bus", "a proud chin lift"),
                ("this bus is going to the depot", "an announcer voice; he lets go with one hand and holds it as if at a microphone"),
                ("You owe them one sentence", "one finger up, both hands back on the phone after"),
                ("I wish you well", "gentle"),
                ("get off at your stop", "a firm nod")],
         centerpiece="THE DEPOT ANNOUNCEMENT",
         final="he fumbles for the button to stop recording; the frame tilts",
         physics="close front-camera wide distortion, the phone shaking slightly in his hands, golden light flaring at the frame edge",
         mood="indignant, warm, funny",
         first_frame="a too-close selfie held in both hands on the brownstone stoop at golden hour, a squinting, baffled look, the camel coat collar visible",
         split="I told you."),
    dict(id="L8", fmt="A", loc="armchair", light="evening", outfit="evening",
         cam=("propped", "the glass of water on the side table, at a 45-degree angle"),
         framing="45-degree medium close-up, chest-up, the ring and chain clearly visible on his cardigan.",
         props=None,
         direction="the story of the ring",
         motive="Angie's laugh",
         goal="share the secret without self-pity",
         obstacle="grief",
         tactic="he keeps it light with the sheriff joke, then lets it go quiet",
         beats=[("This is my wedding ring", "THE SIGNATURE: he lifts the ring on the chain between two fingers"),
                ("so it lives here", "he lets it rest back on his chest"),
                ("I got bigger", "a self-deprecating chuckle"),
                ("Angie laughed so hard", "a warm smile, eyes glistening but bright"),
                ("like a sheriff's badge", "he searches for the words, then taps the ring like a badge"),
                ("She passed two years later", "the register breaks: quiet, eyes drop"),
                ("We said goodnight every night", "his eyes come back up, steady"),
                ("through the bathroom door", "a small laugh through it")],
         centerpiece="THE QUIET TURN on 'She passed two years later'",
         final="he glances at the framed photo on the side table",
         physics="the thin gold chain catching the lamp light, the leather creaking",
         mood="tender, wry, warm",
         first_frame="sitting in the leather armchair in evening lamp light in a navy cardigan, two fingers lifting the gold wedding band on its thin chain, a gentle look at the lens",
         split="I got bigger."),
    dict(id="L9", fmt="A", loc="stoop", light="golden", outfit="stoop",
         cam=("companion", "at his eye level, sitting on the step below him"),
         framing="Medium shot, he sits on the top step, a touch off-center.",
         props=None,
         direction="the Tuesday rule",
         motive="low-pressure honesty",
         goal="make Tuesday dates sound obviously smart",
         obstacle="admitting his own first date was a Saturday",
         tactic="two fingers up, mock-weary of Saturdays, a sheepish ending",
         beats=[("Lou's rule number two", "two fingers up"),
                ("Not Saturday. Tuesday.", "a firm little headshake, then a nod"),
                ("Saturday's a whole production", "hands spread like a big show"),
                ("Nobody expects nothing", "a relaxed shrug"),
                ("A coffee and a walk", "one finger"),
                ("home by eight for your programs", "a contented pat on his knee"),
                ("our first was a Saturday", "a sheepish look away"),
                ("do as I say, not as I did", "a wagging finger and a chuckle")],
         centerpiece="THE SHEEPISH CONFESSION",
         final="he leans back on his elbows on the step",
         physics="leaves skittering, the coat folds, long golden shadows",
         mood="easy, twinkly",
         first_frame="sitting on the brownstone stoop at golden hour in a camel coat, two fingers raised, a twinkly look at the lens",
         split="Nobody expects nothing."),
    dict(id="L10", fmt="A", loc="armchair", light="afternoon", outfit="default",
         cam=("propped", "a short stack of hardback books on the side table, at a 45-degree angle"),
         framing="45-degree medium shot, chest-up.",
         props="a folded sheet of paper with illegible printed writing (Nicky printed the comment), held in his hand from frame one",
         direction="answering a viewer's question from the comments",
         motive="Angie went first, and it changed his life",
         goal="give the viewer permission to go first",
         obstacle="the embarrassing story",
         tactic="he reads the question off the paper, then answers to the lens",
         beats=[("Somebody wrote", "he lifts the folded paper and peers at it"),
                ("will I look desperate?", "he lowers the paper, a pitying look over it"),
                ("Desperate is waiting three days", "one finger up"),
                ("Text first. Call first! Whatever.", "a self-correction, then a dismissive wave"),
                ("the one with the guts", "a fist to his chest"),
                ("left a message with my boss", "eyes wide, scandalised all over again"),
                ("I married her", "a soft, proud grin"),
                ("I'll answer the good ones", "he waggles the paper")],
         centerpiece="THE SCANDALISED MEMORY",
         final="he folds the paper and tucks it into his cardigan pocket",
         physics="the paper crinkling, the leather creaking",
         mood="playful, encouraging",
         first_frame="sitting in the leather armchair holding a folded sheet of paper with illegible writing, peering at it, warm afternoon light",
         split="the one with the guts."),
    dict(id="L11", fmt="A", loc="lunch", light="day", outfit="sunday",
         cam=("companion", "across the table at chest height, sitting"),
         framing="Medium shot across the table, he speaks to the lens.",
         props=None,
         direction="a calm crisis protocol for a silent phone",
         motive="he hates seeing kids wait by the phone",
         goal="the viewer sends one message, then puts the phone away",
         obstacle="the viewer's panic",
         tactic="slow, calming, word for word, and the drawer gesture",
         beats=[("They went quiet.", "a sympathetic look"),
                ("Don't send fifteen question marks", "a headshake, a little wince"),
                ("Call once.", "one finger"),
                ("exactly this", "he leans in, deliberate"),
                ("I'd love to see you Thursday", "he says the words slowly, like dictating"),
                ("the phone goes in a drawer", "he mimes sliding a drawer shut"),
                ("both are answers", "kind eyes"),
                ("Link in my bio", "a small nod")],
         centerpiece="THE DRAWER",
         final="he pats the table: done",
         physics="the napkin in his collar, family murmur off-frame",
         mood="calm, kind, firm",
         first_frame="sitting at the Sunday lunch table with a napkin tucked into his collar, a sympathetic look at the lens",
         split="exactly this."),
    dict(id="L12", fmt="A", loc="stoop", light="golden", outfit="stoop",
         cam=("companion", "at his eye level, sitting on the step below him"),
         framing="Medium shot, he sits on the top step.",
         props=None,
         direction="a masterclass in asking someone out",
         motive="eleven cents, and a day and a time",
         goal="the viewer asks someone this week",
         obstacle="'sometime' culture",
         tactic="he kills 'sometime', then dictates the words",
         beats=[("How to ask somebody out", "a businesslike look"),
                ("with eleven cents", "he pats his pocket"),
                ("we should hang out sometime", "a vague, limp hand"),
                ("Sometime is never, kid", "a flat look"),
                ("I like talking to you", "he softens, demonstrating"),
                ("on Tuesday, around six?", "one finger, then two"),
                ("A day and a time.", "he taps his knee twice"),
                ("thanks for being straight with me", "a gracious nod"),
                ("And you mean it", "steady")],
         centerpiece="THE DEMONSTRATION",
         final="he raises his eyebrows: got it?",
         physics="leaves skittering, the coat folds, long golden shadows",
         mood="practical, warm",
         first_frame="sitting on the brownstone stoop at golden hour in a camel coat, a businesslike look at the lens",
         split="Sometime is never, kid."),
    dict(id="L13", fmt="A", loc="armchair", light="evening", outfit="evening",
         cam=("propped", "a short stack of hardback books on the side table, at a 45-degree angle"),
         framing="45-degree medium shot, chest-up; the glass of water on the side table at frame edge.",
         props="a glass of water on the side table (lifted only in the final beat)",
         direction="the kind exit",
         motive="the legend of Angie's one-sentence breakup",
         goal="the viewer ends it kindly and briefly",
         obstacle="people over-explain, and he has to keep it short himself",
         tactic="he dictates the words, then 'Then you stop' with a flat hand",
         beats=[("Like a grown-up, kid", "a firm look"),
                ("Not with a meme", "a disgusted little headshake"),
                ("I've realized", "slow, dictating"),
                ("I wish you well", "gentle"),
                ("Then you stop.", "a flat hand: stop"),
                ("don't apologize six times", "fingers flicking away"),
                ("Short is kind", "a quiet nod"),
                ("a Christmas card for forty years", "a delighted chuckle")],
         centerpiece="THE FLAT HAND 'Then you stop.'",
         final="he sips from the glass of water",
         physics="the lamp light on the chain, the leather creaking",
         mood="firm, kind, wry",
         first_frame="sitting in the leather armchair in evening lamp light in a navy cardigan, a firm kind look at the lens, a glass of water on the side table",
         split="I wish you well."),
    dict(id="L14", fmt="A", loc="lunch", light="day", outfit="sunday",
         cam=("companion", "across the table at chest height, sitting"),
         framing="Medium shot across the table, he speaks to the lens (and teases Nicky behind it).",
         props=None,
         direction="teasing Nicky while teaching the first thirty seconds",
         motive="his grandkids' fear of the phone baffles him",
         goal="make calling feel doable",
         obstacle="Nicky, filming, embarrassed",
         tactic="he teases Nicky, then dictates the opener",
         beats=[("You kids are scared of the phone", "a pitying look"),
                ("Nicky, you are", "he points at Nicky behind the phone"),
                ("word for word", "a lean in"),
                ("no, your name", "a self-correcting chuckle"),
                ("Is now a good time?", "polite, demonstrating"),
                ("I wanted to hear your voice", "a soft smile"),
                ("you need a reason", "one finger"),
                ("when's better?", "a gracious shrug")],
         centerpiece="THE POINT AT NICKY",
         final="he winks at Nicky",
         physics="the napkin in his collar, cutlery sounds off-frame",
         mood="teasing, warm, practical",
         first_frame="sitting at the Sunday lunch table with a napkin tucked into his collar, a pitying, teasing look at the lens",
         split="use your own name."),
    dict(id="L15", fmt="A", loc="lunch", light="day", outfit="sunday",
         cam=("propped", "the sugar bowl on the table, a little below his eye level"),
         framing="Medium close-up, chest-up, the sugar bowl's rim soft in the near foreground.",
         props=None,
         direction="rule three, with a family story",
         motive="Nicky's lost chance",
         goal="the viewer turns their phone face down",
         obstacle="he's still annoyed at Nicky",
         tactic="he demonstrates with an imaginary phone, tells the story, and ends deadpan",
         beats=[("Lou's rule number three", "three fingers up"),
                ("the phone goes face down", "he flips an imaginary phone face down on the cloth"),
                ("like a little TV", "a mocking little frame made with his fingers"),
                ("she put her phone in her bag", "an approving nod"),
                ("She asked my sister about her hip!", "a delighted, impressed look"),
                ("kid, don't mess this up", "a stern whisper"),
                ("He messed it up.", "a deadpan look straight into the lens"),
                ("Rule number four next week", "four fingers, a twinkle")],
         centerpiece="THE DEADPAN 'He messed it up.'",
         final="he shakes his head slowly",
         physics="the napkin in his collar, the lace cloth under his hands",
         mood="wry, warm",
         first_frame="sitting at the Sunday lunch table with a napkin tucked into his collar, three fingers raised, a sugar bowl in the near foreground",
         split="like a little TV."),
]
