import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Upload, CheckCircle, AlertCircle, FileCode2 } from 'lucide-react';
import { validateStoryboardJson } from '../lib/ai/json-importer';
import { useSettingsStore } from '../store/settings-store';
import { db } from '../db/database';
import { v4 as uuid } from 'uuid';
import type { Project } from '../types/project';

export function ImportPage() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const language = useSettingsStore((s) => s.language);
  const [jsonText, setJsonText] = useState('');
  const [errors, setErrors] = useState<string[]>([]);
  const [isValid, setIsValid] = useState<boolean | null>(null);

  const handleValidate = () => {
    if (!jsonText.trim()) return;
    const result = validateStoryboardJson(jsonText);
    setIsValid(result.isValid);
    setErrors(result.errors);
  };

  const handleImport = async () => {
    const result = validateStoryboardJson(jsonText);
    if (!result.isValid || !result.data) return;

    const data = result.data;
    const project: Project = {
      id: uuid(),
      name: data.projectName,
      type: data.projectType,
      description: '',
      status: 'draft',
      language: data.language || language,
      storyboard: {
        intro: data.intro,
        shots: data.shots,
        outro: data.outro,
        musicTrack: null,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await db.projects.add(project);
    navigate(`/project/${project.id}`);
  };

  const sampleJson = JSON.stringify(
    {
      version: '1.0',
      projectName: 'Talking Character - Wedding',
      projectType: 'talking-character',
      language: 'he',
      intro: {
        title: 'Intro',
        backgroundDescription: 'Elegant wedding hall entrance with fairy lights',
        textOverlay: 'Welcome!',
        duration: 5,
        musicReference: 'Elegant orchestral intro',
        showLogo: true,
      },
      shots: [
        {
          title: 'Character Greeting',
          environment: {
            setting: 'Wedding hall main stage',
            lighting: 'Purple and gold lighting',
            props: 'Flower arrangements',
            atmosphere: 'Festive and warm',
          },
          character: {
            appearance: '3D cartoon character',
            outfit: 'Festive tuxedo',
            expression: 'Smiling',
            action: 'Waving at camera',
          },
          dialogue: { text: 'Welcome everyone!', voiceStyle: 'Cheerful', language: 'he' },
          cameraAngle: 'medium-shot',
          duration: 8,
          mood: 'festive',
          transition: 'fade',
        },
      ],
      outro: {
        title: 'Outro',
        backgroundDescription: 'Party scene with confetti',
        textOverlay: 'Thank You!',
        duration: 5,
        musicReference: 'Upbeat closing music',
        showLogo: true,
      },
    },
    null,
    2
  );

  return (
    <div className="max-w-4xl mx-auto p-6">
      <h2 className="text-2xl font-bold text-text mb-2">{t('ai.claudeImport')}</h2>
      <p className="text-text-muted mb-6">
        {language === 'he'
          ? 'הדבק כאן JSON שנוצר על ידי Claude Code כדי לייבא סטוריבורד שלם'
          : 'Paste JSON generated by Claude Code to import a complete storyboard'}
      </p>

      {/* Instructions */}
      <div className="bg-surface-light border border-border rounded-xl p-4 mb-6">
        <div className="flex items-center gap-2 mb-3">
          <FileCode2 className="w-5 h-5 text-primary-400" />
          <h3 className="font-semibold text-text text-sm">
            {language === 'he' ? 'איך להשתמש' : 'How to use'}
          </h3>
        </div>
        <ol className="text-sm text-text-muted space-y-1 list-decimal ps-5">
          {language === 'he' ? (
            <>
              <li>פתח את Claude Code או כל ממשק של Claude</li>
              <li>בקש מ-Claude ליצור סטוריבורד בפורמט JSON (העתק את הדוגמה למטה)</li>
              <li>הדבק את ה-JSON כאן ולחץ "בדוק"</li>
              <li>אם תקין, לחץ "ייבא סטוריבורד"</li>
            </>
          ) : (
            <>
              <li>Open Claude Code or any Claude interface</li>
              <li>Ask Claude to create a storyboard in JSON format (copy the example below)</li>
              <li>Paste the JSON here and click "Validate"</li>
              <li>If valid, click "Import Storyboard"</li>
            </>
          )}
        </ol>
      </div>

      {/* JSON Input */}
      <div className="mb-4">
        <textarea
          value={jsonText}
          onChange={(e) => {
            setJsonText(e.target.value);
            setIsValid(null);
            setErrors([]);
          }}
          rows={14}
          placeholder={t('ai.pasteJson')}
          className="w-full bg-surface border border-border rounded-xl px-4 py-3 text-sm text-text font-mono placeholder:text-text-muted focus:outline-none focus:border-primary-500 resize-y"
          dir="ltr"
        />
      </div>

      {/* Validation status */}
      {isValid !== null && (
        <div
          className={`mb-4 p-3 rounded-lg flex items-start gap-2 ${
            isValid
              ? 'bg-green-900/30 border border-green-500/30'
              : 'bg-red-900/30 border border-red-500/30'
          }`}
        >
          {isValid ? (
            <CheckCircle className="w-5 h-5 text-green-400 shrink-0 mt-0.5" />
          ) : (
            <AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
          )}
          <div>
            <p className={`text-sm font-medium ${isValid ? 'text-green-300' : 'text-red-300'}`}>
              {isValid ? t('ai.validJson') : t('ai.invalidJson')}
            </p>
            {errors.map((err, i) => (
              <p key={i} className="text-xs text-red-400 mt-0.5">{err}</p>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center gap-3 mb-8">
        <button
          onClick={handleValidate}
          disabled={!jsonText.trim()}
          className="px-4 py-2 rounded-lg bg-surface-lighter hover:bg-border text-text text-sm transition-colors disabled:opacity-40"
        >
          {t('ai.validate')}
        </button>
        <button
          onClick={handleImport}
          disabled={!isValid}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary-600 hover:bg-primary-700 text-white text-sm font-medium transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <Upload className="w-4 h-4" />
          {t('ai.importBtn')}
        </button>
      </div>

      {/* Example JSON */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="font-semibold text-text text-sm">
            {language === 'he' ? 'דוגמת JSON' : 'Example JSON'}
          </h3>
          <button
            onClick={() => {
              navigator.clipboard.writeText(sampleJson);
            }}
            className="text-xs text-primary-400 hover:text-primary-300"
          >
            {language === 'he' ? 'העתק דוגמה' : 'Copy example'}
          </button>
        </div>
        <pre
          className="bg-surface border border-border rounded-xl p-4 text-xs text-text-muted font-mono overflow-auto max-h-60"
          dir="ltr"
        >
          {sampleJson}
        </pre>
      </div>
    </div>
  );
}
